language: objective-c
osx_image: xcode7.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE="Example/BufferSlider.xcworkspace"
  - IOS_FRAMEWORK_SCHEME="BufferSlider"
  - IOS_EXAMPLE_SCHEME="BufferSlider"
  - IOS_SDK=iphonesimulator9.2
  matrix:
    - DESTINATION="OS=9.2,name=iPhone 6S Plus"     SCHEME="$IOS_EXAMPLE_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="NO"
script:
  - set -o pipefail && xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint BufferSlider.podspec --allow-warnings
